#!/usr/bin/env bash
# Block Claude/AI attribution anywhere user-supplied prose lands in
# permanent git/GitHub history. Covers:
#   - git commit (commit messages)
#   - gh pr create / edit / comment / review (PR body, comments, reviews)
#   - gh issue create / edit / comment (issue body / comments)
#   - gh release create / edit (release notes)
#   - gh api ... (catches direct REST POSTs to PR/issue/release endpoints)
set -e
INPUT=$(cat)
COMMAND=$(echo "$INPUT" | jq -r '.tool_input.command // empty')
if ! echo "$COMMAND" | grep -qE '^(git commit|gh (pr|issue|release) (create|edit|comment|review)|gh api )'; then
    exit 0
fi
if echo "$COMMAND" | grep -qiE '(co-authored-by.*claude|co-authored-by.*anthropic|generated with claude|generated by claude)'; then
    echo "BLOCKED: Claude attribution is forbidden in commits and PRs. Remove any Co-Authored-By, 'Generated with Claude', or AI references." >&2
    exit 2
fi
