#!/usr/bin/env bash
# Block Claude/AI attribution anywhere user-supplied prose lands in
# permanent git/GitHub history. Covers:
#   - git commit (commit messages)
#   - gh pr create / edit / comment / review (PR body, comments, reviews)
#   - gh issue create / edit / comment (issue body / comments)
#   - gh release create / edit (release notes)
#   - gh api ... (catches direct REST POSTs to PR/issue/release endpoints)
set -e
INPUT=$(cat)
COMMAND=$(echo "$INPUT" | jq -r '.tool_input.command // empty')
if ! echo "$COMMAND" | grep -qE '^(git commit|gh (pr|issue|release) (create|edit|comment|review)|gh api )'; then
    exit 0
fi
# The `.{0,4}` after "generated with/by" tolerates a SHORT separator
# between the verb and "claude", so the canonical Claude Code footer
# `Generated with [Claude Code](…)` (markdown `[`), `generated by the
# claude model` (` the `, 4 chars), etc. all match — the previous
# adjacent-words form missed every one of these. The bound is deliberately
# tiny (≤4 chars: a bracket, ` the `, ` a `, `by `) so benign prose like
# "generated with care" never false-positives. `🤖 generated` catches the
# robot-emoji signature the harness emits directly.
if echo "$COMMAND" | grep -qiE 'co-authored-by.*(claude|anthropic)|generated (with|by) .{0,4}claude|🤖 generated'; then
    echo "BLOCKED: Claude attribution is forbidden in commits and PRs. Remove any Co-Authored-By, 'Generated with Claude', or AI references." >&2
    exit 2
fi
