#!/usr/bin/env bash
# Block Claude/AI attribution anywhere user-supplied prose lands in
# permanent git/GitHub history. Covers:
#   - git commit (commit messages)
#   - gh pr create / edit / comment / review (PR body, comments, reviews)
#   - gh issue create / edit / comment (issue body / comments)
#   - gh release create / edit (release notes)
#   - gh api ... (catches direct REST POSTs to PR/issue/release endpoints)
set -e
INPUT=$(cat)
COMMAND=$(echo "$INPUT" | jq -r '.tool_input.command // empty')
# Anchors + their rationale live in the shared lib (one home for the
# whole git-/gh-guard family).
ANCHOR_LIB="$(dirname "$0")/git_anchor.sh"
if [ ! -r "$ANCHOR_LIB" ]; then
    # Fail CLOSED: a missing/unreadable lib (corrupted plugin cache) must
    # block, not silently disarm the guard — only exit 2 blocks in the
    # PreToolUse contract.
    echo "BLOCKED: guard anchor lib missing at $ANCHOR_LIB — refusing the command rather than running unguarded." >&2
    exit 2
fi
source "$ANCHOR_LIB"
if ! echo "$COMMAND" | grep -qE "(${GIT_ANCHOR}commit\b|${GH_ANCHOR}(pr|issue|release)[[:space:]]+(create|edit|comment|review)\b|${GH_ANCHOR}api\b)"; then
    exit 0
fi
# The `.{0,4}` after "generated with/by" tolerates a SHORT separator
# between the verb and "claude", so the canonical Claude Code footer
# `Generated with [Claude Code](…)` (markdown `[`), `generated by the
# claude model` (` the `, 4 chars), etc. all match — the previous
# adjacent-words form missed every one of these. The bound is deliberately
# tiny (≤4 chars: a bracket, ` the `, ` a `, `by `) so benign prose like
# "generated with care" never false-positives. `🤖 generated` catches the
# robot-emoji signature the harness emits directly. The remaining
# alternatives mirror the newer credit phrasings in
# forge.pr_squash_comment.AI_ATTRIBUTION_PATTERNS — when that tuple
# gains a phrase, add its vendor-qualified form here by hand (this hook
# is tuned for raw commit-message noise, so it stays deliberately
# narrower than the Python list).
if echo "$COMMAND" | grep -qiE 'co-authored-by.*(claude|anthropic)|generated (with|by) .{0,4}claude|🤖 generated|assisted by ai|ai-generated|with claude code|authored by claude'; then
    echo "BLOCKED: Claude attribution is forbidden in commits and PRs. Remove any Co-Authored-By, 'Generated with Claude', or AI references." >&2
    exit 2
fi
