"""Shared GitHub comment plumbing for forge's PR-comment CLIs.

``forge-pr-squash-comment`` and ``forge-pr-wrapup`` each own a comment
lifecycle on a PR (post, find their own earlier comments by a marker,
retire them). The ``gh`` calls behind that — paginated listing, post,
delete, edit — and the FOUNDATION §2 attribution gate every posted body
must pass are identical for both, so they live here once. Policy (what
each CLI validates, what "retire" means) stays per CLI.
"""

from __future__ import annotations

import json
import logging
import subprocess
from typing import Any, Final

from forge.git_utils import gh_api, own_login


logger = logging.getLogger(__name__)

# Comment listing walks every page of a long-lived PR; the 10s default
# in `gh_api` is sized for git hooks, not for `--paginate`.
GH_LIST_TIMEOUT: Final[int] = 30

# Phrases that signal AI attribution. Case-insensitive substring match.
# Phrases, not bare vendor tokens: FOUNDATION §2 forbids *credit lines*,
# while forge itself mandates filenames containing the vendor name
# (`CLAUDE.md`, `.claude/agents/...`) that PR content must be able to
# cite. Bare tokens are handled by the path-aware backstop in
# `validate_no_ai_attribution`. (`claude-hooks/block_claude_attribution.sh`
# enforces the same policy with its own regex, but only on hand-typed
# `git`/`gh` Bash commands — content flowing through a CLI's internal
# subprocess calls is gated HERE only, so this validator cannot lean on
# the hook as a backstop. Phrase-list parity with the hook via the
# `forge-gen-commit-types`-style sync mechanism is a tracked follow-up.)
AI_ATTRIBUTION_PATTERNS: Final[tuple[str, ...]] = (
    "co-authored-by:",
    "🤖",
    "generated with",
    "generated by",
    "assisted by ai",
    "ai-generated",
    "with claude code",
    "authored by claude",
)

# Bare vendor tokens rejected by the backstop unless the containing
# whitespace token is shaped like a file forge itself would cite:
# a `.claude`/`claude-hooks` dotdir/dir prefix, or a known repo file
# extension. Deliberately NOT "contains any `/` or `.`" — that blanket
# form exempts credit disguises like `generated-with/claude` or
# `made-by.claude` (security review, PR #270).
_VENDOR_TOKENS: Final[tuple[str, ...]] = ("claude", "anthropic")

_CITABLE_PREFIXES: Final[tuple[str, ...]] = (".claude", "claude-hooks")

_CITABLE_EXTENSIONS: Final[frozenset[str]] = frozenset(
    {"md", "py", "sh", "yml", "yaml", "toml", "json", "txt", "rst"}
)


class ValidationError(ValueError):
    """Raised when PR-comment content fails a FOUNDATION rule."""


def _cites_repo_file(token: str) -> bool:
    """Return whether *token* is shaped like a repo path forge mandates.

    Args:
        token: One whitespace-delimited, punctuation-stripped token.

    Returns:
        ``True`` for tokens with a forge-mandated dir prefix
        (``.claude``, ``claude-hooks``) or a known file extension —
        the shapes PR content legitimately cites.
    """
    return token.startswith(_CITABLE_PREFIXES) or (
        token.rpartition(".")[2] in _CITABLE_EXTENSIONS
    )


def validate_no_ai_attribution(text: str) -> None:
    """Reject Claude / AI attribution per FOUNDATION §2.

    Two layers: attribution *phrases* anywhere in the text, then a
    bare-vendor-token backstop that exempts tokens shaped like files
    forge mandates (:func:`_cites_repo_file`) — PR content must be
    able to name `CLAUDE.md` or `.claude/agents/x.md` while a bare
    "thanks Claude" credit still fails.

    Args:
        text: The content about to be posted (any markdown).

    Raises:
        ValidationError: When the text contains a phrase from
            :data:`AI_ATTRIBUTION_PATTERNS`, or a vendor token outside
            a repo-file-shaped context (case-insensitive).
    """
    blob = text.lower()
    for pat in AI_ATTRIBUTION_PATTERNS:
        if pat in blob:
            msg = (
                f"AI attribution pattern detected: {pat!r}. "
                "FOUNDATION §2 forbids Claude/AI attribution in commits "
                "and PR content."
            )
            raise ValidationError(msg)
    for raw in blob.split():
        # Sentence punctuation must not disguise a bare mention as
        # path-shaped: "Claude." is a credit, "claude.md" is a file,
        # ".claude" is a dotdir — so quotes strip from both ends but
        # `.,!?…` only from the right, where prose puts them. Stripped
        # to a fixpoint: interleavings like "`CLAUDE.md`." shed the
        # trailing dot AND the then-exposed backtick.
        token = raw
        while True:
            stripped = token.strip("`\"'()[]{}<>*_~").rstrip(".,!?;:—-")
            if stripped == token:
                break
            token = stripped
        if _cites_repo_file(token):
            continue
        for vendor in _VENDOR_TOKENS:
            if vendor in token:
                msg = (
                    f"AI attribution pattern detected: {vendor!r} "
                    f"(in {token!r}). Path or file references like "
                    "`CLAUDE.md` are allowed; a bare vendor mention is "
                    "not. FOUNDATION §2 forbids Claude/AI attribution "
                    "in commits and PR content."
                )
                raise ValidationError(msg)


def parse_paged_json(raw: str) -> list[Any]:
    """Flatten ``gh api --paginate --jq '[...]'`` output into one list.

    Args:
        raw: Stdout from the paginated call — one JSON array per page,
            newline-separated.

    Returns:
        Every page's entries in page order — the element type follows
        the caller's ``--jq`` projection (mappings or bare timestamps);
        unparseable lines are skipped with a warning rather than
        aborting the run.
    """
    items: list[Any] = []
    for line in raw.splitlines():
        if not line.strip():
            continue
        try:
            page = json.loads(line)
        except json.JSONDecodeError:
            logger.warning("skipping unparseable gh api page: %.60s", line)
            continue
        items.extend(page)
    return items


def list_marker_comments(pr_number: int, marker: str) -> list[dict[str, object]] | None:
    """Return this identity's comments on *pr_number* carrying *marker*, oldest first.

    Only comments authored by the login ``gh`` is signed in as
    (:func:`forge.git_utils.own_login`) are returned: on a public repo
    anyone can plant the marker, and the callers delete or rewrite what
    this function hands them. A marker comment by someone else is logged
    and skipped, never touched.

    Args:
        pr_number: GitHub PR number.
        marker: The invisible HTML-comment marker a CLI stamps on its
            own posts.

    Returns:
        One ``{"id", "body", "created_at", "author"}`` mapping per own
        marker-carrying comment, or ``None`` when the listing call failed
        or the own identity is unknown — a distinction callers need:
        "none posted yet" and "could not look" demand different behaviour.
    """
    me = own_login()
    if me is None:
        logger.warning("cannot determine the gh login; marker comments left untouched")
        return None
    raw = gh_api(
        f"repos/{{owner}}/{{repo}}/issues/{pr_number}/comments",
        "--paginate",
        "--jq",
        "[.[] | {id, body, created_at, author: .user.login}]",
        timeout=GH_LIST_TIMEOUT,
    )
    if raw is None:
        return None
    own: list[dict[str, object]] = []
    for comment in parse_paged_json(raw):
        if marker not in str(comment.get("body", "")):
            continue
        if comment.get("author") != me:
            logger.warning(
                "skipping marker comment %s by %s — not posted by %s",
                comment.get("id"),
                comment.get("author"),
                me,
            )
            continue
        own.append(comment)
    return own


def post_new_comment(pr_number: int, body: str) -> int:
    """Post *body* as a new comment on PR ``pr_number``.

    Args:
        pr_number: GitHub PR number.
        body: Pre-built comment body.

    Returns:
        Exit code from ``gh pr comment``.
    """
    proc = subprocess.run(
        ["gh", "pr", "comment", str(pr_number), "--body-file", "-"],
        input=body,
        text=True,
        check=False,
    )
    return proc.returncode


def delete_comment(comment_id: int) -> bool:
    """Delete one issue comment by id.

    Args:
        comment_id: GitHub issue/PR comment id (numeric).

    Returns:
        ``True`` when the API accepted the delete. A dedicated
        subprocess call rather than :func:`gh_api`, whose "empty stdout
        is a failure" contract cannot see the difference between a
        successful ``204 No Content`` and a rejected call.
    """
    proc = subprocess.run(
        [
            "gh",
            "api",
            "-X",
            "DELETE",
            f"repos/{{owner}}/{{repo}}/issues/comments/{comment_id}",
        ],
        capture_output=True,
        text=True,
        check=False,
    )
    if proc.returncode != 0:
        logger.warning(
            "could not delete superseded comment %d (exit %d): %s",
            comment_id,
            proc.returncode,
            proc.stderr.strip(),
        )
        return False
    return True


def patch_comment(comment_id: int, body: str) -> bool:
    """Replace one issue comment's body in place.

    Args:
        comment_id: GitHub issue/PR comment id (numeric).
        body: The full new body.

    Returns:
        ``True`` when the API accepted the edit; a failure only warns —
        an un-retired earlier comment is a cosmetic residue, never a
        reason to fail the post that superseded it.
    """
    proc = subprocess.run(
        [
            "gh",
            "api",
            "-X",
            "PATCH",
            f"repos/{{owner}}/{{repo}}/issues/comments/{comment_id}",
            "-f",
            "body=@-",
        ],
        input=body,
        capture_output=True,
        text=True,
        check=False,
    )
    if proc.returncode != 0:
        logger.warning(
            "could not edit superseded comment %d (exit %d): %s",
            comment_id,
            proc.returncode,
            proc.stderr.strip(),
        )
        return False
    return True
