"""Shared GitHub comment plumbing for forge's PR-comment CLIs.

``forge-pr-squash-comment`` and ``forge-pr-wrapup`` each own a comment
lifecycle on a PR (post, find their own earlier comments by a marker,
retire them). The ``gh`` calls behind that — paginated listing, post,
delete, edit — and the FOUNDATION §2 attribution gate every posted body
must pass are identical for both, so they live here once. Policy (what
each CLI validates, what "retire" means) stays per CLI.
"""

from __future__ import annotations

import functools
import importlib.util
import json
import logging
import re
import subprocess
import unicodedata
from importlib import metadata
from typing import Any, Final

from forge.git_utils import gh_api, own_login
from forge.pr_delta import fenced_line_indexes


logger = logging.getLogger(__name__)

# Comment listing walks every page of a long-lived PR; the 10s default
# in `gh_api` is sized for git hooks, not for `--paginate`.
GH_LIST_TIMEOUT: Final[int] = 30

# Phrases that signal AI attribution. Case-insensitive substring match.
# Phrases, not bare vendor tokens: FOUNDATION §2 forbids *credit lines*,
# while forge itself mandates filenames containing the vendor name
# (`CLAUDE.md`, `.claude/agents/...`) that PR content must be able to
# cite. Bare tokens are handled by the path-aware backstop in
# `validate_no_ai_attribution`. (`claude-hooks/block_claude_attribution.sh`
# enforces the same policy with its own regex, but only on hand-typed
# `git`/`gh` Bash commands — content flowing through a CLI's internal
# subprocess calls is gated HERE only, so this validator cannot lean on
# the hook as a backstop. Phrase-list parity with the hook via the
# `forge-gen-commit-types`-style sync mechanism is a tracked follow-up.)
AI_ATTRIBUTION_PATTERNS: Final[tuple[str, ...]] = (
    "co-authored-by:",
    "🤖",
    "generated with",
    "generated by",
    "assisted by ai",
    "ai-generated",
    "with claude code",
    "authored by claude",
)

# "generated with" / "generated by" match only as whole words (so
# "regenerated with" and "auto-generated by" are not credit lines) and
# not when the next word names one of forge's own tools ("generated by
# forge-gen-api-digest") — an installed forge CLI, an importable
# `forge.*` module, or bare "forge". A word that merely starts with
# "forge" (`forge-copilot`, `forge.ai`) is not a tool and still matches,
# as do "Generated with Copilot" and "generated by an LLM"; a
# vendor-named form also trips the token backstop.
_GENERATED_PHRASES: Final[frozenset[str]] = frozenset(
    {"generated with", "generated by"}
)
_GENERATED_RE: Final[re.Pattern[str]] = re.compile(r"(?<![\w-])generated\s+(with|by)\b")
_NEXT_WORD_RE: Final[re.Pattern[str]] = re.compile(r"\s+`?([\w.-]+)")
_FORGE_DISTRIBUTION: Final[str] = "forge-scripts"

# Characters dropped before matching, so nothing invisible can split
# "generated by" or "claude" past the checks: every format character
# (zero-width, bidi controls, tag characters, invisible operators) and
# combining mark (variation selectors, grapheme joiners) by Unicode
# category, plus control characters (NUL and the like; tab and newlines
# stay so words are not merged) and the Hangul fillers that render blank
# but are letters.
# NFKC first folds look-alikes (fullwidth letters, compatibility forms)
# onto their plain counterparts. Escaped, never literal, in this source.
_INVISIBLE_CATEGORIES: Final[frozenset[str]] = frozenset({"Cf", "Mn", "Me"})
_BLANK_LETTERS: Final[frozenset[str]] = frozenset({"\u115f", "\u1160", "\u3164"})
_KEPT_CONTROLS: Final[frozenset[str]] = frozenset({"\t", "\n", "\r"})


def _normalise(text: str) -> str:
    """Return *text* folded for matching: marks and invisibles dropped, lowercased.

    Args:
        text: Raw content.

    Returns:
        The normalised text the phrase and vendor checks read.
    """
    # Decompose first so a mark attached to a base letter ("c" + U+0301)
    # is a separate character the filter can drop, then recompose.
    decomposed = unicodedata.normalize("NFKD", text)
    kept = "".join(
        ch
        for ch in decomposed
        if unicodedata.category(ch) not in _INVISIBLE_CATEGORIES
        and ch not in _BLANK_LETTERS
        and (unicodedata.category(ch) != "Cc" or ch in _KEPT_CONTROLS)
    )
    return unicodedata.normalize("NFKC", kept).lower()


# Characters shed from both ends of a token (quotes, markdown emphasis,
# brackets, and the backslash of an escaped backtick), and sentence
# punctuation shed from the right only.
_STRIP_BOTH: Final[str] = "`\"'()[]{}<>*_~\\"
_STRIP_RIGHT: Final[str] = ".,!?;:—-"

# Suffixes a citation may carry after the file name: a possessive, a
# `#fragment` anchor, or a `:line` number. Shed ONLY when testing
# whether a token cites a repo file — the vendor check always sees the
# whole token, so `made-by#claude` cannot hide behind the anchor rule.
_POSSESSIVES: Final[tuple[str, ...]] = ("'s", "\u2019s")
_CITATION_SUFFIX_RE: Final[re.Pattern[str]] = re.compile(r"(?:#[\w.-]*|:\d+)$")

# Bare vendor tokens rejected by the backstop unless the containing
# whitespace token is shaped like a file forge itself would cite:
# a `.claude`/`claude-hooks` dotdir/dir prefix, or a known repo file
# extension. Deliberately NOT "contains any `/` or `.`" — that blanket
# form exempts credit disguises like `generated-with/claude` or
# `made-by.claude` (security review, PR #270).
_VENDOR_TOKENS: Final[tuple[str, ...]] = ("claude", "anthropic")

_CITABLE_PREFIXES: Final[tuple[str, ...]] = (".claude", "claude-hooks")

_CITABLE_EXTENSIONS: Final[frozenset[str]] = frozenset(
    {"md", "py", "sh", "yml", "yaml", "toml", "json", "txt", "rst"}
)


class ValidationError(ValueError):
    """Raised when PR-comment content fails a FOUNDATION rule."""


def _cites_repo_file(token: str) -> bool:
    """Return whether *token* is shaped like a repo path forge mandates.

    Args:
        token: One whitespace-delimited, punctuation-stripped token.

    Returns:
        ``True`` for tokens with a forge-mandated dir prefix
        (``.claude``, ``claude-hooks``) or a known file extension —
        the shapes PR content legitimately cites.
    """
    return token.startswith(_CITABLE_PREFIXES) or (
        token.rpartition(".")[2] in _CITABLE_EXTENSIONS
    )


def _strip_token(raw: str) -> str:
    """Shed quotes from both ends and sentence punctuation from the right.

    Sentence punctuation must not disguise a bare mention as path-shaped:
    "Claude." is a credit, "claude.md" is a file, ".claude" is a dotdir —
    so sentence punctuation strips only from the right, where prose puts
    it. Stripped
    to a fixpoint: interleavings like "`CLAUDE.md`." shed the trailing
    dot AND the then-exposed backtick.

    Args:
        raw: One whitespace-delimited token.

    Returns:
        The token with surrounding quotes and trailing punctuation removed.
    """
    token = raw
    while True:
        stripped = token.strip(_STRIP_BOTH).rstrip(_STRIP_RIGHT)
        if stripped == token:
            return token
        token = stripped


def _is_citation(token: str) -> bool:
    """Return whether *token* cites a repo file, suffixes allowed.

    Accepts the shapes prose puts after a file name — `CLAUDE.md's`,
    `CLAUDE.md#anchor`, `CLAUDE.md:42` — by shedding them to a fixpoint
    before :func:`_cites_repo_file`'s exact-tail check, which stays the
    security boundary (`made-by.claude's` still ends in `claude`).

    Args:
        token: A token already passed through :func:`_strip_token`.

    Returns:
        ``True`` when the token, minus citation suffixes, is repo-file-shaped.
    """
    base = token
    while True:
        shed = base
        for suffix in _POSSESSIVES:
            shed = shed.removesuffix(suffix)
        shed = _strip_token(_CITATION_SUFFIX_RE.sub("", shed))
        if shed == base:
            return _cites_repo_file(base)
        base = shed


@functools.cache
def _forge_cli_names() -> frozenset[str]:
    """Return the console-script names the installed forge declares.

    Returns:
        The lowercased script names, or an empty set when forge's
        distribution metadata cannot be read (the allowlist then holds
        only bare "forge" — failing toward refusal, never acceptance).
    """
    try:
        dist = metadata.distribution(_FORGE_DISTRIBUTION)
    except metadata.PackageNotFoundError:
        return frozenset()
    return frozenset(
        ep.name.lower() for ep in dist.entry_points if ep.group == "console_scripts"
    )


def _names_forge_tool(word: str) -> bool:
    """Return whether *word* names forge itself, a forge CLI, or a forge module.

    Args:
        word: The lowercased word following "generated with/by".

    Returns:
        ``True`` for bare "forge", an installed forge console script, or an
        importable ``forge.*`` module; ``False`` for anything merely
        starting with "forge".
    """
    word = word.rstrip(".-")
    if word == "forge" or word in _forge_cli_names():
        return True
    if not word.startswith("forge."):
        return False
    try:
        return importlib.util.find_spec(word) is not None
    except (ImportError, ValueError):
        return False


def _phrase_hit(blob: str) -> str | None:
    """Return the attribution phrase found in lowercased *blob*, if any.

    Args:
        blob: The full lowercased text, fenced blocks included.

    Returns:
        The matched phrase, or ``None``.
    """
    for generated in _GENERATED_RE.finditer(blob):
        following = _NEXT_WORD_RE.match(blob, generated.end())
        if following and _names_forge_tool(following.group(1)):
            continue
        return f"generated {generated.group(1)}"
    for pat in AI_ATTRIBUTION_PATTERNS:
        if pat not in _GENERATED_PHRASES and pat in blob:
            return pat
    return None


def _outside_closed_fences(blob: str) -> str:
    """Return *blob* without its CLOSED fenced blocks.

    The fence exemption fails closed: a fence that is never closed runs to
    the end under CommonMark, so honouring it would let one stray opener
    exempt the rest of the text. Real evidence blocks are closed, so the
    trailing unclosed run is scanned like prose.

    Args:
        blob: Lowercased text.

    Returns:
        The lines outside every closed fenced block, newline-joined.
    """
    lines = blob.splitlines()
    fenced = fenced_line_indexes(lines)
    # A sentinel line lands inside a fence only when the last fence is open.
    if len(lines) in fenced_line_indexes([*lines, "x"]):
        start = len(lines)
        while start - 1 in fenced:
            start -= 1
        fenced = {i for i in fenced if i < start}
    return "\n".join(line for i, line in enumerate(lines) if i not in fenced)


def _vendor_hit(blob: str) -> tuple[str, str] | None:
    """Return ``(vendor, token)`` for the first bare vendor mention in *blob*.

    Args:
        blob: Lowercased text to scan token by token.

    Returns:
        The vendor name and the token containing it, or ``None`` when every
        vendor mention sits inside a repo-file citation.
    """
    for raw in blob.split():
        token = _strip_token(raw)
        if _is_citation(token):
            continue
        for vendor in _VENDOR_TOKENS:
            if vendor in token:
                return vendor, token
    return None


def validate_no_ai_attribution(
    text: str, *, exempt_fenced_vendor_tokens: bool = False
) -> None:
    """Reject Claude / AI attribution per FOUNDATION §2.

    Two layers: attribution *phrases* anywhere in the text, then a
    bare-vendor-token backstop that exempts tokens shaped like files
    forge mandates (:func:`_is_citation`) — PR content must be able to
    name `CLAUDE.md` or `.claude/agents/x.md` while a bare "thanks
    Claude" credit still fails. The phrase layer always reads the whole
    text; only the backstop can skip fenced blocks, because quoted
    evidence (a diff, tool output) may name the product without
    crediting it, while an explicit credit phrase is a credit anywhere.

    Args:
        text: The content about to be posted (any markdown).
        exempt_fenced_vendor_tokens: Skip the bare-vendor backstop inside
            fenced code blocks. For wrap-ups, whose evidence blocks quote
            exact bytes; never for text that becomes commit history.

    Raises:
        ValidationError: When the text contains an attribution phrase
            (:data:`AI_ATTRIBUTION_PATTERNS`), or a vendor token outside
            a repo-file-shaped context (case-insensitive).
    """
    blob = _normalise(text)
    phrase = _phrase_hit(blob)
    if phrase is not None:
        msg = (
            f"AI attribution pattern detected: {phrase!r}. "
            "FOUNDATION §2 forbids Claude/AI attribution in commits "
            "and PR content."
        )
        raise ValidationError(msg)
    scanned = _outside_closed_fences(blob) if exempt_fenced_vendor_tokens else blob
    hit = _vendor_hit(scanned)
    if hit is not None:
        vendor, token = hit
        msg = (
            f"AI attribution pattern detected: {vendor!r} "
            f"(in {token!r}). Path or file references like "
            "`CLAUDE.md`, `CLAUDE.md's` or `CLAUDE.md:42` are allowed; "
            "a bare vendor mention is not. FOUNDATION §2 forbids "
            "Claude/AI attribution in commits and PR content."
        )
        raise ValidationError(msg)


def parse_paged_json(raw: str, *, strict: bool = False) -> list[Any]:
    """Flatten ``gh api --paginate --jq '[...]'`` output into one list.

    Args:
        raw: Stdout from the paginated call — one JSON array per page,
            newline-separated.
        strict: Raise on an unparseable page instead of skipping it — for
            callers that must fail closed, where a partial listing would
            read as a complete one.

    Returns:
        Every page's entries in page order — the element type follows
        the caller's ``--jq`` projection (mappings or bare timestamps);
        unparseable lines are skipped with a warning rather than
        aborting the run, unless *strict*.

    Raises:
        json.JSONDecodeError: When *strict* and a page is not JSON.
    """
    items: list[Any] = []
    for line in raw.splitlines():
        if not line.strip():
            continue
        try:
            page = json.loads(line)
        except json.JSONDecodeError:
            if strict:
                raise
            logger.warning("skipping unparseable gh api page: %.60s", line)
            continue
        items.extend(page)
    return items


def list_marker_comments(
    pr_number: int, marker: str, *, anchored: bool = False
) -> list[dict[str, object]] | None:
    """Return this identity's comments on *pr_number* carrying *marker*, oldest first.

    Only comments authored by the login ``gh`` is signed in as
    (:func:`forge.git_utils.own_login`) are returned: on a public repo
    anyone can plant the marker, and the callers delete or rewrite what
    this function hands them. A marker comment by someone else is logged
    and skipped, never touched.

    Args:
        pr_number: GitHub PR number.
        marker: The invisible HTML-comment marker a CLI stamps on its
            own posts.
        anchored: Match only a comment whose body *starts* with the
            marker (after leading whitespace). Needed by a CLI whose own
            posts always open with the marker, because another comment
            may quote its marker mid-text — and the caller deletes what
            matches. The default substring match suits markers that sit
            at the end of a body, or bodies later wrapped in
            ``<details>``.

    Returns:
        One ``{"id", "body", "created_at", "author"}`` mapping per own
        marker-carrying comment, or ``None`` when the listing call failed
        or the own identity is unknown — a distinction callers need:
        "none posted yet" and "could not look" demand different behaviour.
    """
    me = own_login()
    if me is None:
        logger.warning("cannot determine the gh login; marker comments left untouched")
        return None
    raw = gh_api(
        f"repos/{{owner}}/{{repo}}/issues/{pr_number}/comments",
        "--paginate",
        "--jq",
        "[.[] | {id, body, created_at, author: .user.login}]",
        timeout=GH_LIST_TIMEOUT,
    )
    if raw is None:
        return None
    own: list[dict[str, object]] = []
    for comment in parse_paged_json(raw):
        body = str(comment.get("body", ""))
        found = body.lstrip().startswith(marker) if anchored else marker in body
        if not found:
            continue
        if comment.get("author") != me:
            logger.warning(
                "skipping marker comment %s by %s — not posted by %s",
                comment.get("id"),
                comment.get("author"),
                me,
            )
            continue
        own.append(comment)
    return own


def post_new_comment(pr_number: int, body: str) -> int:
    """Post *body* as a new comment on PR ``pr_number``.

    Args:
        pr_number: GitHub PR number.
        body: Pre-built comment body.

    Returns:
        Exit code from ``gh pr comment``.
    """
    proc = subprocess.run(
        ["gh", "pr", "comment", str(pr_number), "--body-file", "-"],
        input=body,
        text=True,
        check=False,
    )
    return proc.returncode


def delete_comment(comment_id: int) -> bool:
    """Delete one issue comment by id.

    Args:
        comment_id: GitHub issue/PR comment id (numeric).

    Returns:
        ``True`` when the API accepted the delete. A dedicated
        subprocess call rather than :func:`gh_api`, whose "empty stdout
        is a failure" contract cannot see the difference between a
        successful ``204 No Content`` and a rejected call.
    """
    proc = subprocess.run(
        [
            "gh",
            "api",
            "-X",
            "DELETE",
            f"repos/{{owner}}/{{repo}}/issues/comments/{comment_id}",
        ],
        capture_output=True,
        text=True,
        check=False,
    )
    if proc.returncode != 0:
        logger.warning(
            "could not delete superseded comment %d (exit %d): %s",
            comment_id,
            proc.returncode,
            proc.stderr.strip(),
        )
        return False
    return True


def patch_comment(comment_id: int, body: str) -> bool:
    """Replace one issue comment's body in place.

    Args:
        comment_id: GitHub issue/PR comment id (numeric).
        body: The full new body.

    Returns:
        ``True`` when the API accepted the edit; a failure only warns —
        an un-retired earlier comment is a cosmetic residue, never a
        reason to fail the post that superseded it.
    """
    proc = subprocess.run(
        [
            "gh",
            "api",
            "-X",
            "PATCH",
            f"repos/{{owner}}/{{repo}}/issues/comments/{comment_id}",
            # `-F`, never `-f`: only `--field` gives `@` its documented
            # meaning, so `@-` reads the body from stdin. `--raw-field`
            # sends static strings, which made this PATCH overwrite the
            # comment with the two literal characters `@-` — a valid
            # request, a success exit, and the collapsed text gone.
            # `--field`'s type conversion is not a hazard here: it acts on
            # the literal `key=value` text, so once `@-` has redirected to
            # stdin the bytes are sent verbatim. Verified against `gh`
            # itself — a body of `true`, `null`, `123` or `@file` each
            # serialises as a JSON string, never a bool, number or nested
            # file read.
            "-F",
            "body=@-",
        ],
        input=body,
        capture_output=True,
        text=True,
        check=False,
    )
    if proc.returncode != 0:
        logger.warning(
            "could not edit superseded comment %d (exit %d): %s",
            comment_id,
            proc.returncode,
            proc.stderr.strip(),
        )
        return False
    return True
