r"""forge-pr-squash-comment — post the squash-merge message and keep it last.

The message reaches GitHub's squash dialog by hand, so the comment
carries its two halves in two separate fences: the title in one, the
3-5 bullet body in the other, each a one-gesture copy into the matching
field. GitHub prefills the title field from the PR title, so a posting
run also **forces the PR title to match** the title it posts — prefill
and message never drift apart.

Every posting run leaves exactly one squash comment, and leaves it as
the PR's newest comment — the human merging scrolls to the bottom, not
through the review history.

Usage:

    forge-pr-squash-comment --pr 61 \\
        --title "feat(#60): pr-manager delta-mode + verified-at" \\
        --bullet "pr_delta.py centralizes thresholds and regex" \\
        --bullet "5 reporter agents stamp verified-at SHA" \\
        --bullet "audit enforces the contract by name allowlist"
        # syncs the PR title, posts a fresh comment, then deletes the
        # older squash comments

    forge-pr-squash-comment --dry-run --title ... --bullet ...
        # prints the wrapped body to stdout, no gh call

    forge-pr-squash-comment --pr 61
        # no bullets: re-posts the existing squash comment verbatim at
        # the bottom after later PR activity, quiet no-op when it is
        # already newest. Runs automatically from the
        # `keep_squash_comment_last` Claude Code hook

Rules (FOUNDATION §6 "Squash-merge messages"):

- title matches conventional-commit ``<type>(...)?: <subject>``
- 3-5 ``--bullet`` entries
- total whitespace-split word count (title + bullets) ≤ 50
- no Claude / AI attribution patterns

Output: the body posted to GitHub is the literal text below (the inner
fences are real ``` blocks, not escapes):

    <!-- forge:squash-merge-message -->
    **Squash-merge message** — copy each fence into the matching field
    of the squash dialog. The PR title is already synced to the title.

    **Title**

    ```
    <title>
    ```

    **Body**

    ```
    - <bullet 1>
    - <bullet 2>
    - <bullet 3>
    ```
"""

from __future__ import annotations

import argparse
import json
import logging
import re
import subprocess
import sys
from typing import Any, Final

from forge.git_utils import configure_cli_logging, gh_api


configure_cli_logging()
logger = logging.getLogger(__name__)


# Canonical source: `forge-gen-commit-types` renders the shell hook's
# regex from this tuple and FOUNDATION §6 names it by path.
CONVENTIONAL_COMMIT_TYPES: Final[tuple[str, ...]] = (
    "feat",
    "fix",
    "refactor",
    "test",
    "docs",
    "chore",
    "perf",
    "ci",
    "build",
    "style",
    "revert",
)

# Conventional commit: `<type>(<scope>)?: <subject>` — scope optional,
# allows multiple `#N` refs separated by commas inside parens.
TITLE_RE: Final[re.Pattern[str]] = re.compile(
    r"^(?P<type>" + "|".join(CONVENTIONAL_COMMIT_TYPES) + r")"
    r"(?:\((?P<scope>[^)]+)\))?"
    r": (?P<subject>.+)$",
)

MIN_BULLETS: Final[int] = 3
MAX_BULLETS: Final[int] = 5
MAX_WORDS: Final[int] = 50

# Invisible in rendered markdown, greppable in the raw body: how a later
# run recognizes the squash comments it must supersede. Same convention
# as `forge:c4:*` / `forge:badges:*` managed blocks.
SQUASH_MARKER: Final[str] = "<!-- forge:squash-merge-message -->"

# Comment listing walks every page of a long-lived PR; the 10s default
# in `gh_api` is sized for git hooks, not for `--paginate`.
_GH_LIST_TIMEOUT: Final[int] = 30

# Phrases that signal AI attribution. Case-insensitive substring match.
# Phrases, not bare vendor tokens: FOUNDATION §2 forbids *credit lines*,
# while forge itself mandates filenames containing the vendor name
# (`CLAUDE.md`, `.claude/agents/...`) that a squash message must be able
# to cite. Bare tokens are handled by the path-aware backstop in
# `_validate_no_ai_attribution`. (`claude-hooks/block_claude_attribution.sh`
# enforces the same policy with its own regex, but only on hand-typed
# `git`/`gh` Bash commands — content flowing through this CLI's internal
# subprocess calls is gated HERE only, so this validator cannot lean on
# the hook as a backstop. Phrase-list parity with the hook via the
# `forge-gen-commit-types`-style sync mechanism is a tracked follow-up.)
AI_ATTRIBUTION_PATTERNS: Final[tuple[str, ...]] = (
    "co-authored-by:",
    "🤖",
    "generated with",
    "generated by",
    "assisted by ai",
    "ai-generated",
    "with claude code",
    "authored by claude",
)

# Bare vendor tokens rejected by the backstop unless the containing
# whitespace token is shaped like a file forge itself would cite:
# a `.claude`/`claude-hooks` dotdir/dir prefix, or a known repo file
# extension. Deliberately NOT "contains any `/` or `.`" — that blanket
# form exempts credit disguises like `generated-with/claude` or
# `made-by.claude` (security review, PR #270).
_VENDOR_TOKENS: Final[tuple[str, ...]] = ("claude", "anthropic")

_CITABLE_PREFIXES: Final[tuple[str, ...]] = (".claude", "claude-hooks")

_CITABLE_EXTENSIONS: Final[frozenset[str]] = frozenset(
    {"md", "py", "sh", "yml", "yaml", "toml", "json", "txt", "rst"}
)


def _cites_repo_file(token: str) -> bool:
    """Return whether *token* is shaped like a repo path forge mandates.

    Args:
        token: One whitespace-delimited, punctuation-stripped token.

    Returns:
        ``True`` for tokens with a forge-mandated dir prefix
        (``.claude``, ``claude-hooks``) or a known file extension —
        the shapes a squash message legitimately cites.
    """
    return token.startswith(_CITABLE_PREFIXES) or (
        token.rpartition(".")[2] in _CITABLE_EXTENSIONS
    )


class ValidationError(ValueError):
    """Raised when the input fails a FOUNDATION §6 squash-merge rule."""


def _validate_title(title: str) -> None:
    """Reject titles outside the conventional-commit format.

    Args:
        title: Raw title string.

    Raises:
        ValidationError: When the title is empty, longer than one line,
            or does not match :data:`TITLE_RE`.
    """
    if not title.strip():
        msg = "title is empty"
        raise ValidationError(msg)
    if "\n" in title:
        msg = "title must be a single line"
        raise ValidationError(msg)
    if not TITLE_RE.match(title):
        msg = (
            f"title {title!r} is not conventional-commit format. "
            f"Expected '<type>(<scope>)?: <subject>' where type is one of: "
            f"{', '.join(CONVENTIONAL_COMMIT_TYPES)}"
        )
        raise ValidationError(msg)


def _validate_bullets(bullets: list[str]) -> None:
    """Enforce bullet count + non-empty content.

    Args:
        bullets: List of ``--bullet`` strings as passed by the caller.

    Raises:
        ValidationError: When the count is outside ``[MIN_BULLETS,
            MAX_BULLETS]`` or any bullet is whitespace-only.
    """
    n = len(bullets)
    if not MIN_BULLETS <= n <= MAX_BULLETS:
        msg = f"got {n} bullet(s); FOUNDATION §6 requires {MIN_BULLETS}-{MAX_BULLETS}"
        raise ValidationError(msg)
    for i, b in enumerate(bullets, start=1):
        if not b.strip():
            msg = f"bullet {i} is empty"
            raise ValidationError(msg)


def _validate_word_count(title: str, bullets: list[str]) -> None:
    """Enforce the ≤ ``MAX_WORDS`` cap on title + bullets combined.

    Args:
        title: Squash title.
        bullets: Bullet strings.

    Raises:
        ValidationError: When the total whitespace-split word count
            exceeds :data:`MAX_WORDS`.
    """
    total = len(title.split()) + sum(len(b.split()) for b in bullets)
    if total > MAX_WORDS:
        msg = (
            f"squash-merge message is {total} words; FOUNDATION §6 caps at {MAX_WORDS}"
        )
        raise ValidationError(msg)


def _validate_no_ai_attribution(title: str, bullets: list[str]) -> None:
    """Reject Claude / AI attribution per FOUNDATION §2.

    Two layers: attribution *phrases* anywhere in the text, then a
    bare-vendor-token backstop that exempts tokens shaped like files
    forge mandates (:func:`_cites_repo_file`) — a squash message must
    be able to name `CLAUDE.md` or `.claude/agents/x.md` while a bare
    "thanks Claude" credit still fails.

    Args:
        title: Squash title.
        bullets: Bullet strings.

    Raises:
        ValidationError: When the text contains a phrase from
            :data:`AI_ATTRIBUTION_PATTERNS`, or a vendor token outside
            a repo-file-shaped context (case-insensitive).
    """
    blob = "\n".join([title, *bullets]).lower()
    for pat in AI_ATTRIBUTION_PATTERNS:
        if pat in blob:
            msg = (
                f"AI attribution pattern detected: {pat!r}. "
                "FOUNDATION §2 forbids Claude/AI attribution in commits "
                "and PR content."
            )
            raise ValidationError(msg)
    for raw in blob.split():
        # Sentence punctuation must not disguise a bare mention as
        # path-shaped: "Claude." is a credit, "claude.md" is a file,
        # ".claude" is a dotdir — so quotes strip from both ends but
        # `.,!?…` only from the right, where prose puts them. Stripped
        # to a fixpoint: interleavings like "`CLAUDE.md`." shed the
        # trailing dot AND the then-exposed backtick.
        token = raw
        while True:
            stripped = token.strip("`\"'()[]{}<>*_~").rstrip(".,!?;:—-")
            if stripped == token:
                break
            token = stripped
        if _cites_repo_file(token):
            continue
        for vendor in _VENDOR_TOKENS:
            if vendor in token:
                msg = (
                    f"AI attribution pattern detected: {vendor!r} "
                    f"(in {token!r}). Path or file references like "
                    "`CLAUDE.md` are allowed; a bare vendor mention is "
                    "not. FOUNDATION §2 forbids Claude/AI attribution "
                    "in commits and PR content."
                )
                raise ValidationError(msg)


def build_body(title: str, bullets: list[str]) -> str:
    """Build the GitHub comment body around a validated message.

    Two fences behind the :data:`SQUASH_MARKER`, one per field of
    GitHub's squash dialog: the title, then the body. Separate fences
    because each is copied on its own — a single block holding both
    would have to be split by hand after pasting. Caller is responsible
    for having passed validated inputs (or running :func:`validate`
    first).

    Args:
        title: Squash title (single line, conventional-commit form).
        bullets: 3-5 bullet strings.

    Returns:
        Markdown body suitable for ``gh pr comment --body-file -``.
    """
    bullet_lines = "\n".join(f"- {b}" for b in bullets)
    fence = "```"
    return (
        f"{SQUASH_MARKER}\n"
        "**Squash-merge message** — copy each fence verbatim into the "
        "matching field of the squash dialog. The PR title is synced to "
        "the title below, so GitHub's prefill already matches.\n\n"
        "**Title**\n\n"
        f"{fence}\n{title}\n{fence}\n\n"
        "**Body**\n\n"
        f"{fence}\n{bullet_lines}\n{fence}\n"
    )


def validate(title: str, bullets: list[str]) -> None:
    """Run every FOUNDATION §6 check in order.

    Args:
        title: Squash title.
        bullets: Bullet strings.

    Raises:
        ValidationError: At the first failing rule. The exception
            message names the rule and (when applicable) the observed
            vs. allowed values.
    """
    _validate_title(title)
    _validate_bullets(bullets)
    _validate_word_count(title, bullets)
    _validate_no_ai_attribution(title, bullets)


def _parse_paged_json(raw: str) -> list[Any]:
    """Flatten ``gh api --paginate --jq '[...]'`` output into one list.

    Args:
        raw: Stdout from the paginated call — one JSON array per page,
            newline-separated.

    Returns:
        Every page's entries in page order — the element type follows
        the caller's ``--jq`` projection (mappings or bare timestamps);
        unparseable lines are skipped with a warning rather than
        aborting the run.
    """
    items: list[Any] = []
    for line in raw.splitlines():
        if not line.strip():
            continue
        try:
            page = json.loads(line)
        except json.JSONDecodeError:
            logger.warning("skipping unparseable gh api page: %.60s", line)
            continue
        items.extend(page)
    return items


def _list_squash_comments(pr_number: int) -> list[dict[str, object]] | None:
    """Return this CLI's own comments on *pr_number*, oldest first.

    Args:
        pr_number: GitHub PR number.

    Returns:
        One ``{"id", "body", "created_at"}`` mapping per
        :data:`SQUASH_MARKER`-carrying comment, or ``None`` when the
        listing call itself failed — a distinction the caller needs:
        "no squash comment" and "could not look" demand different
        behaviour.
    """
    raw = gh_api(
        f"repos/{{owner}}/{{repo}}/issues/{pr_number}/comments",
        "--paginate",
        "--jq",
        "[.[] | {id, body, created_at}]",
        timeout=_GH_LIST_TIMEOUT,
    )
    if raw is None:
        return None
    return [
        c for c in _parse_paged_json(raw) if SQUASH_MARKER in str(c.get("body", ""))
    ]


def _latest_activity_at(pr_number: int) -> str | None:
    """Return the newest timestamp across every comment surface of a PR.

    Conversation comments, review-thread replies, and review
    submissions each live behind a different endpoint; a squash comment
    buried by a `/pr-comments` reply is invisible to the conversation
    listing alone.

    Args:
        pr_number: GitHub PR number.

    Returns:
        The newest ISO-8601 UTC timestamp seen (GitHub normalizes to
        ``Z``, so lexicographic order is chronological order), or
        ``None`` when nothing could be read — the caller then re-posts
        rather than assuming the comment is still last.
    """
    endpoints = (
        (f"repos/{{owner}}/{{repo}}/issues/{pr_number}/comments", "created_at"),
        (f"repos/{{owner}}/{{repo}}/pulls/{pr_number}/comments", "created_at"),
        (f"repos/{{owner}}/{{repo}}/pulls/{pr_number}/reviews", "submitted_at"),
    )
    stamps: list[str] = []
    for path, field in endpoints:
        raw = gh_api(
            path,
            "--paginate",
            "--jq",
            f"[.[] | .{field}]",
            timeout=_GH_LIST_TIMEOUT,
        )
        if raw is None:
            return None
        stamps.extend(str(s) for s in _parse_paged_json(raw) if s)
    return max(stamps) if stamps else None


def _post_new_comment(pr_number: int, body: str) -> int:
    """Post *body* as a new comment on PR ``pr_number``.

    Args:
        pr_number: GitHub PR number.
        body: Pre-built comment body.

    Returns:
        Exit code from ``gh pr comment``.
    """
    proc = subprocess.run(
        ["gh", "pr", "comment", str(pr_number), "--body-file", "-"],
        input=body,
        text=True,
        check=False,
    )
    return proc.returncode


def sync_pr_title(pr_number: int, title: str) -> bool:
    """Force the PR title to match the squash title.

    GitHub prefills the squash dialog's title field from the PR title,
    so the two must never disagree: an edited squash title that left
    the PR title behind would put a stale line in the permanent `main`
    commit. Reading first keeps the PR timeline free of no-op title
    events; an unreadable title still takes the write, because a
    redundant edit is cheaper than a silent mismatch.

    Args:
        pr_number: GitHub PR number.
        title: The validated squash title.

    Returns:
        ``True`` when the PR title already matched or was updated;
        ``False`` when the edit was rejected — the caller reports that,
        since the human then has to fix the title field by hand.
    """
    current = gh_api(f"repos/{{owner}}/{{repo}}/pulls/{pr_number}", "--jq", ".title")
    if current == title:
        return True
    proc = subprocess.run(
        ["gh", "pr", "edit", str(pr_number), "--title", title],
        capture_output=True,
        text=True,
        check=False,
    )
    if proc.returncode != 0:
        logger.error(
            "could not sync PR #%d title to %r (exit %d): %s",
            pr_number,
            title,
            proc.returncode,
            proc.stderr.strip(),
        )
        return False
    if current is not None:
        logger.info("PR #%d title updated to match the squash title", pr_number)
    return True


def _delete_comment(comment_id: int) -> bool:
    """Delete one issue comment by id.

    Args:
        comment_id: GitHub issue/PR comment id (numeric).

    Returns:
        ``True`` when the API accepted the delete. A dedicated
        subprocess call rather than :func:`gh_api`, whose "empty stdout
        is a failure" contract cannot see the difference between a
        successful ``204 No Content`` and a rejected call.
    """
    proc = subprocess.run(
        [
            "gh",
            "api",
            "-X",
            "DELETE",
            f"repos/{{owner}}/{{repo}}/issues/comments/{comment_id}",
        ],
        capture_output=True,
        text=True,
        check=False,
    )
    if proc.returncode != 0:
        logger.warning(
            "could not delete superseded squash comment %d (exit %d): %s",
            comment_id,
            proc.returncode,
            proc.stderr.strip(),
        )
        return False
    return True


def _prune(superseded: list[dict[str, object]] | None) -> None:
    """Delete the squash comments a fresh post has replaced.

    Runs after the new comment is live, so a failure here leaves a
    duplicate rather than a PR with no squash message — and never
    changes the exit code.

    Args:
        superseded: Comments captured *before* posting, or ``None``
            when the listing failed.
    """
    if superseded is None:
        logger.warning(
            "could not list existing comments; older squash comments may remain"
        )
        return
    for comment in superseded:
        _delete_comment(int(str(comment["id"])))


def post_squash_comment(pr_number: int, body: str) -> int:
    """Post *body*, then delete the squash comments it supersedes.

    Args:
        pr_number: GitHub PR number.
        body: Pre-built comment body.

    Returns:
        ``0`` on a successful post. Cleanup is best-effort: the caller
        gets the post's exit code, and pruning failures only warn.
    """
    superseded = _list_squash_comments(pr_number)
    rc = _post_new_comment(pr_number, body)
    if rc != 0:
        return rc
    _prune(superseded)
    return 0


def ensure_last(pr_number: int) -> int:
    """Re-post the existing squash comment so it is the newest again.

    What ``--pr`` does when no bullets are given, and what the
    ``keep_squash_comment_last`` hook runs after any command that
    comments on a PR: a quiet no-op while the squash comment is still
    the newest activity, a verbatim re-post (old one deleted) once
    anything — including a review-thread reply — has landed under it.

    Args:
        pr_number: GitHub PR number.

    Returns:
        ``0`` when the comment is last (already, or after re-posting);
        ``1`` when the PR could not be read or carries no squash
        comment to move.
    """
    existing = _list_squash_comments(pr_number)
    if existing is None:
        logger.error("could not read PR #%d comments; --ensure-last aborted", pr_number)
        return 1
    if not existing:
        logger.error(
            "PR #%d has no forge squash comment to move; post one with --bullet first",
            pr_number,
        )
        return 1
    newest_squash = str(existing[-1].get("created_at", ""))
    latest = _latest_activity_at(pr_number)
    if len(existing) == 1 and latest is not None and newest_squash >= latest:
        logger.info("squash comment is already the newest comment on PR #%d", pr_number)
        return 0
    rc = _post_new_comment(pr_number, str(existing[-1]["body"]))
    if rc != 0:
        return rc
    _prune(existing)
    return 0


def main() -> int:
    """Validate the body, post it (or print it), and keep it last.

    Returns:
        ``0`` on success. ``1`` on validation failure (with the
        offending rule named on stderr) or non-zero ``gh`` exit.
    """
    parser = argparse.ArgumentParser(
        prog="forge-pr-squash-comment",
        description=(
            "Post the squash-merge body as the PR's newest comment. "
            "The title is the PR title — GitHub prefills it. "
            "Rules per FOUNDATION §6."
        ),
    )
    target = parser.add_mutually_exclusive_group(required=True)
    target.add_argument(
        "--pr",
        type=int,
        help=(
            "PR number to comment on. With --bullet: syncs the PR title, "
            "posts the message and prunes older squash comments. Without: "
            "re-posts the existing one so it is the newest comment again."
        ),
    )
    target.add_argument(
        "--dry-run",
        action="store_true",
        help="Print the wrapped body to stdout; do not call gh.",
    )
    parser.add_argument(
        "--title",
        default="",
        help=(
            "Squash title (conventional-commit format). Required with "
            "--bullet; the PR title is forced to match it."
        ),
    )
    parser.add_argument(
        "--bullet",
        action="append",
        default=[],
        metavar="TEXT",
        help="Bullet line. Repeat 3-5 times.",
    )
    args = parser.parse_args()

    # Keeping the comment last is the default, not a mode: a bare
    # `--pr N` is the "PR moved on, move the comment" call.
    if args.pr is not None and not args.bullet:
        return ensure_last(args.pr)

    try:
        validate(args.title, args.bullet)
    except ValidationError as exc:
        sys.stderr.write(f"forge-pr-squash-comment: {exc}\n")
        return 1

    body = build_body(args.title, args.bullet)

    if args.dry_run:
        sys.stdout.write(body)
        return 0

    title_synced = sync_pr_title(args.pr, args.title)
    rc = post_squash_comment(args.pr, body)
    if rc != 0:
        return rc
    # The comment is live either way; a failed title sync is still a
    # non-zero run, because the prefill no longer matches what it says.
    return 0 if title_synced else 1


if __name__ == "__main__":
    sys.exit(main())
